#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: posit_na_float

# STEP: vivado_flow
cd /home/ubuntu/PandA-bambu/posit/posit_16_6
vivado -mode batch -nojournal -nolog -source /home/ubuntu/PandA-bambu/posit/posit_16_6/HLS_output//Synthesis/vivado_flow/vivado.tcl


